### ISSUE TITLE
Make the Polyfill kickin also on android 4.0.3

### ISSUE THREAD

**Issue by Bnaya** [eligrey/Blob.js#19]
Android 4.0.3 webview (and maybe also 4.1/2/3, i will verify this)
Have native Blob constructor (what makes the polyfill check to fail)
but its broken.

If you try to do any variation of the constructor 
new Blob(), new Blob([]), new Blob([], {..}) etc...

You will get: 
TypeError: Illegal constructor exception

If you manually activating the polyfill, its looks like its working

**Comment by jimmywarting** [comment]
close?

**Comment by Bnaya** [comment]
why not :)
