### ISSUE TITLE
Implement a FileReader?

### ISSUE THREAD

**Issue by jimmywarting** [eligrey/Blob.js#33]
A way to read the blob data would be grate, whatever its underlying data is (raw, fakeblob, real blob, arraybuffer, whatever) especially for IE9.

```
var fakeBlob new Blob([arraybuffer, fakeBlob, "raw text", arraybufferView]);
```

I think its mandatory that you can read a blob if you can construct one.

```
var fr = new FileReader();
fr.readAsArrayBuffer(fakeBlob); // require typed array polyfill (not by you, but from the author)
fr.readAsText(fakeBlob);
fr.readAsDataURI(fakeBlob);
```

**Comment by jimmywarting** [comment]
I ended up helping github/fetch polyfill and they do more or less depend on Blob & FileReader now when they are starting to use ReadableStream as there underlying source. so they need to convert a stream to a blob and a blob to arrayBuffer or Text

I started to develop a polyfill for the FileReader but wanted to use a other kind of underlying source (a buffer, Uint8Array) since it's more convenient for handling binaries

**Comment by guest271314** [comment]
@jimmywarting  `Uncaught TypeError: Failed to construct 'CustomEvent': 1 argument required, but only 0 present.`

**Comment by jimmywarting** [comment]
@guest271314 fixed

**Comment by guest271314** [comment]
@jimmywarting Is it possible to convert a `Blob` or `File` object to an `ArrayBuffer` without using `FileReader`?  [How to create an ArrayBuffer and data URI from Blob and File objects without FileReader?](http://stackoverflow.com/questions/38195855/how-to-create-an-arraybuffer-and-data-uri-from-blob-and-file-objects-without-fil)
