### ISSUE TITLE
Bower compatibility

### ISSUE THREAD

**Issue by rpavlik** [eligrey/Blob.js#39]
I think this is basically the same issue as https://github.com/eligrey/FileSaver.js/issues/127 - adding a `bower.json` file would make this easier to use.

**Comment by laurafg** [comment]
+1!!

**Comment by nandinga** [comment]
+1

This is also related: https://github.com/eligrey/FileSaver.js/pull/109

The thing is that bower requires the use of semantic versioning. Maybe "2014.11.29" could be a solution that satisfies all?

**Comment by eligrey** [comment]
@nandinga https://twitter.com/sephr/status/542978804441169920 and https://twitter.com/sephr/status/542980376613113856

**Comment by nandinga** [comment]
Sounds fair. If I add the `bower.json` file and PR, will you integrate?

**Comment by eligrey** [comment]
No, but maintaining a bower.json file is not very difficult. You will have to periodically update a downstream fork to be in sync. This repo is for source code collaboration, not syndication with the plethora of package managers and CDNs. If I wanted to support a package manager or CDN I might as well add all of them, as I have no preference over bower/npm/etc.

**Comment by bjornstar** [comment]
#36 and #32 have been sitting there for quite some time.

I've published [blob-polyfill] (https://github.com/bjornstar/blob-polyfill) v1.0.20150320 from my fork on [bower] (http://bower.io/search/?q=blob-polyfill) and [npm] (https://www.npmjs.com/package/blob-polyfill). I have no problems maintaining packages, feel free to send me PRs.

I also incorporated #37 in my release.

I purposely left Blob.js available if you want to that namespace. @eligrey, if you object to anything that I've done here, please get in touch with me.

**Comment by eligrey** [comment]
You are free to name it Blob.js if you want. Also thanks I didn't notice #37. I merged it mainstream as well.

**Comment by eligrey** [comment]
http://bower.io/search/?q=blob-polyfill and https://www.npmjs.com/package/blob-polyfill are the official bower and npm repos.
