### ISSUE TITLE
Suggestion: rename Blob.js folder in bower_components to blobjs

### ISSUE THREAD

**Issue by jshor** [eligrey/Blob.js#43]
The convention for bower packages seems to be all lower case letters or dashes. I suggest renaming the bower folder from "Blob.js" to "blobjs."

**Comment by jimmywarting** [comment]
close... even bower themself suggest that you shouldn't use bower

**Comment by jshor** [comment]
I wrote this issue almost four years ago. Times have changed. I'm closing it now.
