### ISSUE TITLE
Cant use with compatibility.js link : https://gist.github.com/ahhchuu/5823646

### ISSUE THREAD

**Issue by anand0401** [eligrey/Blob.js#52]
i m trying to do a excel download 
these two lines are failing 
var u8_2 = new Uint8Array(atob(ByteArray).split("").map(function(c) {
				return c.charCodeAt(0);
			}));
		var blob = new Blob( [ u8_2 ]);

u8_2 was undefined then i used compatibility.js code to fix it ..but then to fix undefined blob issue  i m using ur code but i m getting error here

if (Uint8Array && (data instanceof ArrayBuffer || data instanceof Uint8Array)) {
error: Invalid operand to 'instanceof': Function expected

both arraybuffer and uint8array comes as undefined...what changes do i need to do?

**Comment by jimmywarting** [comment]
old issue, should be closed.
code has changes since.

**Comment by anand0401** [comment]
Old Issue. Closing the thread
