### ISSUE TITLE
Undefined variable: Uint8Array

### ISSUE THREAD

**Issue by NeilFraser** [eligrey/Blob.js#58]
This line appears to be checking if Uint8Array exists:
https://github.com/eligrey/Blob.js/blob/3eca1d01c802acd6fb02def446dab87191200a15/Blob.js#L192

However my reading of it is that if Uint8Array doesn't exist, the JS runtime would throw an undefined variable error.  Did you mean to use typeof?

**Comment by eligrey** [comment]
`Uint8Array` is defined at https://github.com/eligrey/Blob.js/blob/3eca1d01c802acd6fb02def446dab87191200a15/Blob.js#L64

If you have any other questions feel free to submit additional issues. Cheers!
