### ISSUE TITLE
[Script Loader] SyntaxError: Unexpected string

### ISSUE THREAD

**Issue by chiuan** [eligrey/Blob.js#75]
/node_modules/script-loader/index.js!./src/vendor/Blob.js

rookie and don't know why........maybe need some help.

**Comment by don137067172** [comment]
@chiuan Do you fixed it ?

**Comment by don137067172** [comment]
@chiuan Have you fixed it?

**Comment by wbxyy** [comment]
I create a vue.config.js at root path and add following code ,but i dont know why ,no guarantee
`module.exports = {
  // 当运行 vue-cli-service build 时生成的生产环境构建文件的目录
  outputDir: 'dist',
  // 放置生成的静态资源 (js、css、img、fonts) 的 (相对于 outputDir 的) 目录
  assetsDir: 'assets',
  // 是否在开发环境下通过 eslint-loader 在每次保存时 lint 代码
  lintOnSave: false,
  devServer: {
    open: true,
    host: 'localhost',
    port: '8081',
    https: false,
    hotOnly: false,
    proxy: 'http://localhost:8880'
  },

  chainWebpack: config => {
    // GraphQL Loader
    config.module
      .rule('js')
      .test(/\.exec\.js$/)
      .use('script-loader')
      .loader('script-loader')
      .end()
  }
}`
